### PR TITLE
Check to see if there used to be children before diffing

### PR DESCRIPTION
**Pull request by jakemmarsh**
I was having a problem in my application where, when navigating from one page to another, the mixin would double-count elements when diffing. This resulted in all elements starting `n` pixels from the left, where `n = width of elements * num of elements double-counted`. 

This PR defaults `removed`, `added`, and `moved` to empty arrays and only does the diffing logic of the number of `oldChildren` is greater than 0

### CODE REVIEW

**Comment by eiriklv** [comment]
I've been testing this a bit now, and it seems to introduce some new bugs, where the first 5 items aren't included in the masonry, and will just fall behind in the background of the container. At least this happens for the app running at www.hearsay.me when testing locally. @jakemmarsh - Do you have an example app of your bug happening, so that I can make it work in both cases? :-)

**Comment by jakemmarsh** [comment]
Hm. Unfortunately I'm using this in a node-webkit application that isn't very easily shared/replicated at this point.

I haven't had many items in the container up to this point, so I may have missed some cases. I haven't noticed items falling behind the background though?

**Comment by jakemmarsh** [comment]
Any update on this @eiriklv ? I'm using this fix in multiple production apps now and haven't noticed any of the bugs you mentioned.

**Comment by eiriklv** [comment]
Hey @jakemmarsh! Without an ability to reproduce your bugs it was close to impossible to make both cases work, since the fix you are proposing breaks all of my examples/apps :-P If you can provide an example for me I'm sure we could work this out :-) It can just be something simple that you rip out from your app and stuff into an NW container which I can play around with.

**Comment by jakemmarsh** [comment]
@eiriklv You can see it live at `http://pundittracker.com`. This mixin is used on the home page, search page, and all the category pages. Seems to be working correctly!

**Comment by eiriklv** [comment]
@jakemmarsh Cool :-) It would be awesome if you could rip out a simple/minimal example from your site, where the original mixin bugs out and yours work fine. This way I can make sure that everything works fine on both apps ([hearsay.me](http://hearsay.me) and [pundittracker.com](http://pundittracker.com)) with an additional fix.

**Comment by jakemmarsh** [comment]
Closing, as I believe recent updates have fixed this bug!

**Comment by eiriklv** [comment]
@jakemmarsh that's great! :-)

**Pull request closed without merging**
